# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 168)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_encriptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encriptar.setObjectName("btn_encriptar")
        self.gridLayout.addWidget(self.btn_encriptar, 2, 2, 1, 2)
        self.chave_label = QtWidgets.QLabel(self.centralwidget)
        self.chave_label.setObjectName("chave_label")
        self.gridLayout.addWidget(self.chave_label, 1, 0, 1, 1)
        self.periodo_label = QtWidgets.QLabel(self.centralwidget)
        self.periodo_label.setObjectName("periodo_label")
        self.gridLayout.addWidget(self.periodo_label, 1, 4, 1, 1)
        self.input_periodo = QtWidgets.QSpinBox(self.centralwidget)
        self.input_periodo.setMinimum(2)
        self.input_periodo.setMaximum(999)
        self.input_periodo.setObjectName("input_periodo")
        self.gridLayout.addWidget(self.input_periodo, 1, 5, 1, 1)
        self.btn_chave = QtWidgets.QPushButton(self.centralwidget)
        self.btn_chave.setObjectName("btn_chave")
        self.gridLayout.addWidget(self.btn_chave, 2, 0, 1, 2)
        self.input_chave = QtWidgets.QLineEdit(self.centralwidget)
        self.input_chave.setText("")
        self.input_chave.setObjectName("input_chave")
        self.gridLayout.addWidget(self.input_chave, 1, 1, 1, 3)
        self.btn_decriptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decriptar.setObjectName("btn_decriptar")
        self.gridLayout.addWidget(self.btn_decriptar, 2, 4, 1, 2)
        self.msg_label = QtWidgets.QLabel(self.centralwidget)
        self.msg_label.setObjectName("msg_label")
        self.gridLayout.addWidget(self.msg_label, 0, 0, 1, 1)
        self.input_msg = QtWidgets.QLineEdit(self.centralwidget)
        self.input_msg.setText("")
        self.input_msg.setObjectName("input_msg")
        self.gridLayout.addWidget(self.input_msg, 0, 1, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Encriptador descriptador"))
        self.btn_encriptar.setText(_translate("MainWindow", "Encriptar"))
        self.chave_label.setText(_translate("MainWindow", "Chave"))
        self.periodo_label.setText(_translate("MainWindow", "Periodo"))
        self.btn_chave.setText(_translate("MainWindow", "Gerar nova chave"))
        self.input_chave.setPlaceholderText(_translate("MainWindow", "digite sua chave aqui"))
        self.btn_decriptar.setText(_translate("MainWindow", "Decriptar"))
        self.msg_label.setText(_translate("MainWindow", "Mensagem"))
        self.input_msg.setPlaceholderText(_translate("MainWindow", "digite sua mensagem aqui"))
